### ISSUE TITLE
avr-gcc: error: @C:\Windows\TEMP\ccsC7iRx: Invalid argument

### ISSUE THREAD

**Issue by wuyizheng123456** [AlexIII/t-rex-duino#1]
hey,i got this error info during the compilation:
Archiving built core (caching) in: C:\Windows\TEMP\arduino_cache_995426\core\core_arduino_avr_nano_cpu_atmega328_e8542dfad011fe300fac8042c3582138.a
Linking everything together...
"D:\\arduino-1.8.12-windows (1)\\arduino-1.8.12\\hardware\\tools\\avr/bin/avr-gcc" -w -Os -g -flto -fuse-linker-plugin -Wl,--gc-sections -mmcu=atmega328p -o "C:\\Windows\\TEMP\\arduino_build_169738/t-rex-duino.ino.elf" "C:\\Windows\\TEMP\\arduino_build_169738\\sketch\\t-rex-duino.ino.cpp.o" "C:\\Windows\\TEMP\\arduino_build_169738\\libraries\\SPI\\SPI.cpp.o" "C:\\Windows\\TEMP\\arduino_build_169738/core\\core.a" "-LC:\\Windows\\TEMP\\arduino_build_169738" -lm
avr-gcc: error: @C:\Windows\TEMP\ccsC7iRx: Invalid argument

avr-gcc: fatal error: no input files

compilation terminated.

lto-wrapper.exe: fatal error: D:\arduino-1.8.12-windows (1)\arduino-1.8.12\hardware\tools\avr/bin/avr-gcc returned 1 exit status

compilation terminated.

d:/arduino-1.8.12-windows (1)/arduino-1.8.12/hardware/tools/avr/bin/../lib/gcc/avr/7.3.0/../../../../avr/bin/ld.exe: error: lto-wrapper failed

collect2.exe: error: ld returned 1 exit status

使用 1.0  版本的库 SPI 在文件夹： D:\arduino-1.8.12-windows (1)\arduino-1.8.12\hardware\arduino\avr\libraries\SPI 
使用 2.0  版本的库 EEPROM 在文件夹： D:\arduino-1.8.12-windows (1)\arduino-1.8.12\hardware\arduino\avr\libraries\EEPROM 
exit status 1

**Comment by AlexIII** [comment]
HI! Looks like general Arduino IDE error to me, unrelated to the actual code. Are you sure your IDE installed properly? Try compiling some of built-in examples.

**Comment by wuyizheng123456** [comment]
thank u,i reinstalled the ide,and it works.but when i connect the vcc of the oled to 5v or 3.3v of arduino,the oled heats quickly and its backlight is very dark.

**Comment by AlexIII** [comment]
What kind of display you're using? OLEDs don't have any backlight. In any way, it shouldn't heat up of course, my guess is that either your connections are wrong or the display is toast.

**Comment by wuyizheng123456** [comment]
It's ssd1309 spi 2.42" and bought from ebay,actually only this chip (d1,the black one) heats up.
![1593627715265-1136579143](https://user-images.githubusercontent.com/49754793/86278364-8a8c4500-bbd8-11ea-8856-6e1e40238797.jpg)
Should I connect vcc and ground to an external power supply?

**Comment by wuyizheng123456** [comment]
Hy j got an update,this is the image when it is connected to 3.3V,so you can see it's a little fuzzy and the score is not  very clear.And when it is connected to 5v,i can get a clear and good picture at first but after a while the arduino cant go on working and the whole thing just stops

**Comment by wuyizheng123456** [comment]
![mmexport1593629981081](https://user-images.githubusercontent.com/49754793/86281974-a7c41200-bbde-11ea-9060-d0f67cdd5044.jpg)

**Comment by wuyizheng123456** [comment]
hey i made it,!

**Comment by AlexIII** [comment]
Glad to hear!
